# Generated by Django 5.2.8 on 2025-11-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('salary_paid', 'Salary Paid'), ('salary_pending', 'Salary Pending'), ('payment_processed', 'Payment Processed')], max_length=20),
        ),
    ]
